# letters = ["a","b","c","d"]
# letters.append("e")
# print(letters)

# names = ["junya","becham","jiants","lions"]
# names.append("karthuk")
# names.append("shaq")
# print(names)
# names.insert(0, "tiger")
# print(names)
# names.insert(1, "base")
# print(names)
# names.insert(7, "kobe")
# print(names)
# names.remove("shaq")
# print(names)
# names.remove("becham")
# print(names)
# names.pop()
# print(names)
# names.pop()
# print(names)
# del names[2]
# print(names)
# names.clear()
# print(names)